## Defines default image for flower, server and worker
defaultImage:
  repository: "ic230302"
  name: "paramytr"
  tag: "0.1.2"
  pullPolicy: IfNotPresent

## Define server
server:
# Definde default name
  defaultName: server
  defaultNameOverride: ""
# Define resource requests and limits
  resources:
    requests:
      memory: "100Mi"
      cpu: "250m"
    limits:
      memory: "250Mi"
      cpu: "1000m"

## Define worker
worker:
# Definde default name
  defaultName: worker
  defaultNameOverride: ""
# Define resource requests and limits
  resources:
    requests:
      memory: "250Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

## Define flower
flower:
# Definde default name
  defaultName: flower
  defaultNameOverride: ""
# Define resource requests and limits
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "250Mi"
      cpu: "500m"

## Define broker
broker:
  # Definde default name
  defaultName: broker
  defaultNameOverride: ""
  # Define broker image
  image:
    repository: ""
    name: redis
    tag: latest
    pullPolicy: IfNotPresent
  # Port and database
  port: 6379
  db: 0
  # Define resource requests and limits
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"

## Define backend
backend:
  # Definde default name
  defaultName: backend
  defaultNameOverride: ""
  # Define backend image
  image:
    repository: ""
    name: redis
    tag: latest
    pullPolicy: IfNotPresent
  # Port and databases for optimization results and instances
  port: 6379
  dbResult: 0
  dbInstance: 1
  # Define resource requests and limits
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"


# Apply extra labels to common labels.
extraLabels: {}

# Ingress enablement
ingress:
  enabled: false


# Persistent Volume Claims enablement
persistence:
  enabled: false