## Defines default image for flower, server and worker
defaultImage:
  repository: "ic230302"
  name: "paramytr"
  tag: "0.1.0"
  pullPolicy: IfNotPresent

## Define server
server:
# Define resource requests and limits
  resources:
    requests:
      memory: "100Mi"
      cpu: "250m"
    limits:
      memory: "250Mi"
      cpu: "1000m"

## Define worker
worker:
# Define resource requests and limits
  resources:
    requests:
      memory: "250Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

## Define flower
flower:
# Define resource requests and limits
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "250Mi"
      cpu: "500m"

## Define broker
broker:
  # Define broker image tag and pullPolicy (image is redis)
  image:
    tag: ""
    pullPolicy: IfNotPresent
  # Define resource requests and limits
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"

## Define backend
backend:
  # Define backend image tag and pullPolicy (image is redis)
  image:
    tag: ""
    pullPolicy: IfNotPresent 
  # Define resource requests and limits
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"


# Apply extra labels to common labels.
extraLabels: {}

# Ingress enablement
ingress:
  enabled: false


# Persistent Volume Claims enablement
persistence:
  enabled: false