apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.defaultNameOverride | default .Values.backend.defaultName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "optimizer.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "optimizer.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: backend
        {{- include "optimizer.backendImage" . | nindent 8 }}
        imagePullPolicy: {{ .Values.backend.defaultImage.pullPolicy }}
        resources:
        {{- toYaml .Values.backend.resources | nindent 10 }}
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          timeoutSeconds: 3 # default is to low
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3 # default is to low
        {{- if .Values.persistence.enabled -}}
        volumeMounts:
          - name: backend-volume-mount
            mountPath: /data
        {{- end -}}
      {{- if .Values.persistence.enabled -}}
      volumes:
      - name: backend-volume-mount
        persistentVolumeClaim:
          claimName: backend-pvc
      {{- end -}}