apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        {{- include "optimizer.backendImage" . | nindent 8 }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          timeoutSeconds: 3 # default is to low
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3 # default is to low
        {{- if .Values.persistence.enabled -}}
        volumeMounts:
          - name: backend-volume-mount
            mountPath: /data
        {{- end -}}
      {{- if .Values.persistence.enabled -}}
      volumes:
      - name: backend-volume-mount
        persistentVolumeClaim:
          claimName: backend-pvc
      {{- end -}}