apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: {{ .Release.Namespace }}
  labels:
    app: broker
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        {{- include "optimizer.brokerImage" . | nindent 8 }}
        imagePullPolicy: {{ .Values.broker.image.pullPolicy }}
        resources:
        {{- toYaml .Values.broker.resources | nindent 10 }}
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          timeoutSeconds: 3 # default is to low
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3 # default is to low
