apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.broker.defaultNameOverride | default .Values.broker.defaultName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "optimizer.broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "optimizer.broker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: broker
        {{- include "optimizer.brokerImage" . | nindent 8 }}
        imagePullPolicy: {{ .Values.broker.defaultImage.pullPolicy }}
        resources:
        {{- toYaml .Values.broker.resources | nindent 10 }}
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          timeoutSeconds: 3 # default is to low
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3 # default is to low
