apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flower.defaultNameOverride | default .Values.flower.defaultName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "optimizer.flower.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "optimizer.flower.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: flower
        {{- include "optimizer.defaultImage" . | nindent 8 }}
        imagePullPolicy: {{ .Values.defaultImage.pullPolicy }}
        command: ["sh"]
        args: ["-c", "/simple_optimization_service/flower/start_flower.sh"]
        ports:
        - containerPort: 5555
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5555
          initialDelaySeconds: 90 # takes some time until workers are ready
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5555
          initialDelaySeconds: 90 # takes some time until workers are ready
        resources:
        {{- toYaml .Values.flower.resources | nindent 10 }}
        envFrom:
          - configMapRef:
              name: optimizer-config