apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server.defaultNameOverride | default .Values.server.defaultName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "optimizer.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "optimizer.server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: server
        {{- include "optimizer.defaultImage" . | nindent 8 }}
        imagePullPolicy: {{ .Values.defaultImage.pullPolicy }}
        command: ["uvicorn"]
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        readinessProbe:
          httpGet:
            path: /healthcheck/
            port: 8000
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /healthcheck/
            port: 8000
          initialDelaySeconds: 10
        resources:
        {{- toYaml .Values.server.resources | nindent 10 }}
        envFrom:
          - configMapRef:
              name: optimizer-config
        ports:
        - containerPort: 8000
