apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: {{ .Release.Namespace }}
  labels:
    app: server
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        {{- include "optimizer.defaultImage" . | nindent 8 }}
        imagePullPolicy: {{ .Values.defaultImage.pullPolicy }}
        command: ["uvicorn"]
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        readinessProbe:
          httpGet:
            path: /healthcheck/
            port: 8000
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /healthcheck/
            port: 8000
          initialDelaySeconds: 10
        resources:
        {{- toYaml .Values.server.resources | nindent 10 }}
        env:
        - name: REDIS_URL
          value: "redis://backend-service:6379/0"
        - name: CELERY_BROKER_URL
          value: "redis://broker-service:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://backend-service:6379/1"
        ports:
        - containerPort: 8000
