apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.defaultNameOverride | default .Values.worker.defaultName }}  
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "optimizer.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "optimizer.worker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: worker
        {{- include "optimizer.defaultImage" . | nindent 8 }}
        imagePullPolicy: {{ .Values.defaultImage.pullPolicy }}
        command: ["celery"]
        args: ["-A", "app.workers.celery", "worker", "--loglevel=INFO"]
        livenessProbe:
          exec:
            # bash is needed to replace the environment variable
            command: [
              "bash",
              "-c",
              "celery -A app.workers.celery inspect ping -d celery@$HOSTNAME"
            ]
          initialDelaySeconds: 30  # startup takes some time
          periodSeconds: 60  # default is to high and celery uses a lot cpu/ram for probing (full cycle)
          timeoutSeconds: 10  # default is to low
        resources:
        {{- toYaml .Values.worker.resources | nindent 10 }}
        env:
        - name: REDIS_URL
          value: "redis://backend-service:6379/0"
        - name: CELERY_BROKER_URL
          value: "redis://broker-service:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://backend-service:6379/1"
        ports:
        - containerPort: 8000
