apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
#host Path for single node testing only; WILL NOT WORK in a multi-node cluster; do not use in production!
  hostPath:
    path: "/data/backend-pv"