apiVersion: v1
kind: Service
metadata:
  name: {{ template "optimizer.broker.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  ports:
  - port: 6379
  selector:
    app: broker
  type: ClusterIP
