apiVersion: v1
kind: Service
metadata:
  name: broker-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: broker-service
spec:
  ports:
  - port: 6379
  selector:
    app: broker
  type: ClusterIP
