apiVersion: v1
kind: Service
metadata:
  name: {{ template "optimizer.flower.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5555
  selector:
    app: flower
  type: ClusterIP
