apiVersion: v1
kind: Service
metadata:
  name: flower-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: flower-service
spec:
  ports:
  - port: 5555
  selector:
    app: flower
  type: ClusterIP
