apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: server-service
spec:
  ports:
  - port: 8000
  selector:
    app: server
  type: ClusterIP
