apiVersion: v1
kind: Service
metadata:
  name: {{ template "optimizer.server.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8000
  selector:
    app: server
  type: ClusterIP
