{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
# when deploying to aks (storage will be provisioned automatically)
#  storageClassName: "managed-csi"
  resources:
    requests:
      storage: 200Mi
{{- end -}}
