apiVersion: v1
kind: ConfigMap
metadata:
  name: optimizer-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer.labels" . | nindent 4 }}
data:
  CELERY_BROKER_URL: {{ printf "%s://%s:%v/%v" .Values.broker.image.name (include "optimizer.broker.serviceName" .) (.Values.broker.port) (.Values.broker.db) }}
  CELERY_RESULT_BACKEND: {{ printf "%s://%s:%v/%v" .Values.backend.image.name (include "optimizer.backend.serviceName" .) .Values.backend.port .Values.backend.dbResult }}
  INSTANCE_BACKEND_URL: {{ printf "%s://%s:%v/%v" .Values.backend.image.name (include "optimizer.backend.serviceName" .) .Values.backend.port .Values.backend.dbInstance }}

